api/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('registration/', views.reg_page, name='registration'),
    path('login/', views.login_view, name='login'),
    path('', views.home_page, name='home'),
    path('log_out', views.logout_view, name='log_out'),
    path('profile/', views.profile, name='profile'),
    path('bookings/<int:pk>', views.get_bookings, name='bookings'),
    path('add_event/', views.add_event, name='add_event'),
    path('status/', views.status, name='status'),
    path('search/', views.search_billboards, name='search_page'),
    path('order/<int:pk>/', views.order_page, name='order_page'),
    path('payment/', views.payment, name='payment'),
    path('support/', views.support_page, name='support'),



    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('reset_password/', auth_views.PasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('order/<int:pk>', views.order_page, name='order'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import reg_page
urlpatterns = [
    path('', include('api.urls')),
    path('admin/', admin.site.urls),

]

api/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.core.validators import RegexValidator
from django import forms
from django.contrib.auth.models import User
from django.conf import settings


class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, username, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=150, unique=True)
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone_number = models.CharField(
        max_length=20, unique=True, null=True, blank=True)
    last_login = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


class NumericPhoneField(models.CharField):
    description = "A phone number containing only numeric characters"

    def formfield(self, **kwargs):
        # Apply a regular expression validator to allow only numeric characters
        numeric_validator = RegexValidator(
            r'^[0-9]+$', 'Only numeric characters are allowed.')

        # Include JavaScript to enforce numeric input on the client side
        kwargs['widget'] = forms.TextInput(
            attrs={'pattern': '[0-9]*', 'title': 'Please enter only numeric characters'})
        kwargs['validators'] = [numeric_validator]

        return super().formfield(**kwargs)


def user_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=100, blank=True)
    company = models.CharField(max_length=100, blank=True)
    image = models.ImageField(
        upload_to='profile_images', default='profile_images/acc.png')


class Billboard(models.Model):
    SIZE_CHOICES = [
        ('Small', 'Small'),
        ('Medium', 'Medium'),
        ('Large', 'Large'),
    ]
    CATEGORY_TYPES = [
        ('Traditional Static', 'Traditional Static'),
        ('Digital', 'Digital'),
        ('Mobile', 'Mobile'),
    ]

    type = models.CharField(max_length=100, choices=CATEGORY_TYPES, blank=True)
    category = models.CharField(
        max_length=50, choices=SIZE_CHOICES, blank=True)
    address = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='billboard_images/', blank=True)
    district = models.CharField(max_length=120, blank=True)
    size = models.CharField(max_length=200, blank=True)
    price = models.CharField(max_length=200, blank=True)

    def __str__(self) -> str:
        return self.address


class Booking(models.Model):
    STATUS_CHOICES = [
        ('In progress', 'In progress'),
        ('Canceled', 'Canceled'),
        ('Approved', 'Approved'),
    ]

    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    billboard = models.ForeignKey(Billboard, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    total_cost = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='In progress')

    def __str__(self) -> str:
        return self.customer.username + ' | ' + self.status


class Review(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    comment = models.TextField(blank=True)

api/views.py
from django.shortcuts import render, HttpResponse
from .models import Booking
from datetime import datetime
import os
from pathlib import Path
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegistrationForm, LoginForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model
from django.urls import reverse
from .forms import ProfileForm
from .models import *
from django.db.models import Q


def reg_page(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True
            user.save()

            # Create a profile for the user
            Profile.objects.create(user=user)

            # Send activation email
            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            activation_link = reverse('activate', kwargs={'uidb64': urlsafe_base64_encode(
                force_bytes(user.pk)), 'token': account_activation_token.make_token(user)})
            message = render_to_string('api/app_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'activation_link': activation_link,
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()

            messages.success(
                request, "Registration successful. Just confirm your email")
            return redirect('login')
        else:
            return render(request, 'api/registration.html', {'form': form})
    else:
        form = RegistrationForm()
    return render(request, 'api/registration.html', {'form': form})


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(
                request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
        else:
            messages.error(request, "Invalid username or password")
    else:
        if 'next' in request.GET:
            messages.info(request, 'You need to log in to access this page.')
        form = LoginForm()
    return render(request, 'api/login.html', {'form': form})


def support_page(request):
    return render(request, 'api/support.html')


def home_page(request):
    user = None
    if request.user.is_authenticated:
        user = request.user

    return render(request, 'api/homepage.html', {'user': user})


def logout_view(request):
    logout(request)
    messages.success(request, "You have been logged out.")
    return redirect('home')


@login_required
def profile(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('name')
        user.last_name = request.POST.get('surname')
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.save()

        profile, created = Profile.objects.get_or_create(user=user)
        profile.phone = request.POST.get('phone')
        profile.address = request.POST.get('city')
        profile.company = request.POST.get('company')
        if request.FILES.get('image'):
            profile.image = request.FILES['image']

        profile.save()

        return redirect('/profile')

    return render(request, 'api/profile.html', {'user': request.user})


def foo(request):
    user = None
    print(request.user.id)
    if request.user.is_authenticated:
        user = CustomUser.objects.get(first_name=request.user.first_name)

    return render(request, 'api/booking-page.html', {'user': user})


@login_required
def order_page(request, pk):
    user = request.user if request.user.is_authenticated else None
    billboard = Billboard.objects.get(id=pk)
    bookings = Booking.objects.all()
    print(billboard.image.url)
    return render(request, 'api/order_page.html', {'bill': billboard, 'user': user, 'book': bookings})


def get_bookings(request, pk):
    billboard = get_object_or_404(Billboard, id=pk)
    bookings = Booking.objects.filter(billboard=billboard)

    data = []
    for booking in bookings:
        event = {

            "title": booking.customer.username,
            "start": booking.start_date.strftime('%Y-%m-%d'),
            "end": booking.end_date.strftime('%Y-%m-%d'),

        }

        data.append(event)
    return JsonResponse(data, safe=False)


# def check_overlapping_bookings(request):
#     start_date = request.GET.get('start_date')
#     end_date = request.GET.get('end_date')

#     overlapping_bookings = Booking.objects.filter(
#         start_date__lte=end_date,
#         end_date__gte=start_date
#     ).exists()

#     return JsonResponse({'overlapping': overlapping_bookings})


def add_event(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    billboard_id = request.GET.get('billboard_id', None)
    user_id = request.GET.get('user_id', None)

    overlapping_bookings = Booking.objects.filter(
        Q(start_date__lte=end) & Q(end_date__gte=start) & Q(billboard_id=billboard_id))
    if not overlapping_bookings.exists():
        # Convert start and end dates to datetime objects
        start_date = datetime.strptime(start, '%Y-%m-%d')
        end_date = datetime.strptime(end, '%Y-%m-%d')

        # Calculate duration in days
        days = (end_date - start_date).days

        # Calculate total cost
        cost_per_day = 20000  # Example cost per day
        total_cost = cost_per_day * days

        # Create and save the booking
        booking = Booking.objects.create(
            customer_id=user_id,
            billboard_id=billboard_id,
            start_date=start_date,
            end_date=end_date,
            total_cost=total_cost
        )

        # Optionally, you can return the ID of the created booking along with the total cost
        data = {
            'success': True,
            'message': 'Successfully added booking.',
            'total_cost': total_cost,
            'booking_id': booking.id  # Optionally, include the ID of the created booking
        }
    else:
        data = {
            'success': False,
            'message': 'There are overlapping bookings for the selected dates.'
        }
    return JsonResponse(data)


def status(request):
    user_bookings = Booking.objects.filter(
        customer=request.user).order_by('-id')
    return render(request, 'api/status.html', {'user_bookings': user_bookings})


@login_required
def search_billboards(request):
    # Retrieve all Billboard objects from the database
    billboards = Billboard.objects.all()

    # Assuming you have retrieved the required data for rendering the template
    # For example, billboards and profileId
    context = {
        'billboards': billboards,
    }
    return render(request, 'api/search.html', context)

# views.py


def payment(request):
    # Retrieve the last booking if it exists
    last_booking = Booking.objects.last()

    # Initialize total_price with a default value
    total_price = 0

    # Check if last_booking is not None
    if last_booking:
        total_price = last_booking.total_cost

    if request.method == 'POST':
        # Handle form submission
        first_name = request.POST.get('first_name', '')
        last_name = request.POST.get('last_name', '')
        email = request.POST.get('email', '')
        card_number = request.POST.get('card_number', '')
        expiry_date = request.POST.get('expiry_date', '')
        cvc = request.POST.get('cvc', '')
        cardholder_name = request.POST.get('cardholder_name', '')

        # Here, you would typically validate the form data and process the payment
        # For simplicity, let's just print the data for now
        print("First Name:", first_name)
        print("Last Name:", last_name)
        print("Email:", email)
        print("Card Number:", card_number)
        print("Expiry Date:", expiry_date)
        print("CVC:", cvc)
        print("Cardholder Name:", cardholder_name)

        # You might want to redirect the user to a thank you page or some other page
        return HttpResponse("Payment Successful!")
    else:
        # If it's not a POST request, just render the payment page
        return render(request, 'api/payment.html', {'total_price': total_price})

api/templates/api/app_active_email.html
{% autoescape off %} Hi {{ user.first_name }}, Please click on the link to
confirm your registration: http://{{ domain }}{{ activation_link }}
{%endautoescape %}

api/templates/api/base-site.html
{% extends "admin/base.html" %} {% block title %}{% if subtitle %}{{ subtitle }}
| {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }}{%
endblock %} {% block branding %}
<div id="site-name">
  <a href="{% url 'admin:index' %}">Billboard Manager</a>
</div>
{% if user.is_anonymous %} {% include "admin/color_theme_toggle.html" %} {%
endif %} {% endblock %} {% block nav-global %}{% endblock %}

api/templates/api/booking-page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/booking-page.css' %}">
    <title>Book</title>
  </head>
  <body>
    <div class="main-container">
        <header class="header">
            <h1>HappyClient</h1>
            <div class="buttons">
              <a href="#">Search&Discover</a>
              <a href="#">Services</a>
              <a href="#">Support</a>
            </div>
            <div class="profile-btn">
              {% if user is not None %}
              <a href="{% url 'profile' %}" class="profile-btn-a">
                {{user.first_name}}
                <img src="static/images/acc.png" alt="Profile Image" width="40px"
              /></a>
              {% else %}
              <button>
                <a
                  href="/login"
                  style="
                    text-decoration-line: none;
                    color: #000;
                    font: 1em sans-serif;
                  "
                  >Sign in</a
                >
                /
                <a
                  href="/registration"
                  style="
                    text-decoration-line: none;
                    color: #000;
                    font: 1em sans-serif;
                  "
                  >Sign up</a
                >
              </button>
              {% endif %}
    </div>
  </body>
</html>

api/templates/api/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HomePage</title>

    <link rel="stylesheet" href="{%static 'css/homepage.css'%}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Saira+Semi+Condensed:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="header">
      <div class="nav-container">
        <div class="logo">
          <h1>HappyClient</h1>
        </div>
        <div class="main-buttons">
          <a href="/search">Billboards</a>
          <a href="/status">Status</a>
          <a href="/support">Support</a>
        </div>

        <div class="login-btn">
          {% if user is not None %}
          <a href="{% url 'profile' %}">
            <img
              src="{% static 'images/colorful.png' %}"
              alt=""
              class="profile-img"
              style="width: 60px"
          /></a>

          {% else %}
          <button class="top-btn">
            <a class="sign-inn" href="/login">Sign in</a>
            /
            <a class="sign-up" href="/registration">Sign up</a>
          </button>
          {% endif %}
        </div>
      </div>
      <div class="title-text">
        <span
          >Elevate Your Advertisement,<br />
          Optimize Your Impact</span
        >
      </div>
    </div>

    <div id="about-us" class="main_about_us">
      <div class="about-us-content">
        <div class="about-us-content-text">
          <h2>ABOUT US</h2>
          <p>
            At <span class="title-about">HappyClient</span>, we specialize in
            connecting businesses with premium advertising spaces across the
            city. Our platform simplifies the process of booking billboard
            space, offering a seamless, user-friendly experience from search to
            reservation. With an extensive network of digital and traditional
            billboards, we provide unparalleled access to high-traffic
            locations, ensuring your message reaches its intended audience
            effectively.
          </p>
          <p>
            Your story is unique, and your advertising should be too. Let
            <span class="title-about">HappyClient</span> be the bridge to your
            audience. Get in touch with us to explore the possibilities and
            start making an impact today.
          </p>
        </div>
        <div class="about-us-content-button">
          <a href="#for-advertisers" class="cta">GET STARTED</a>
        </div>
      </div>
    </div>
    <div id="for-advertisers" class="main_for_advertisers">
      <div class="for_advertiers_container">
        <div class="for_advertisers_content">
          <h1>FOR ADVERTISERS</h1>
          <img src="{%static '/images/element1.jpg'%}" alt="imge" />
          <a href="#for_boardonwers" class="for-button">Let's go</a>
        </div>
        <div class="advertisers-text">
          <p>
            Welcome to <span class="title-advertisers">HappyClient</span>, where
            your brand's journey takes a leap into the spotlight. Imagine your
            message, bold and vibrant, capturing the gaze of thousands across
            the city. We make that vision a reality. With
            <span class="title-advertisers">HappyClient</span>, you gain access
            to an unparalleled selection of billboard locations, each chosen for
            maximum visibility and impact. Our intuitive platform offers a
            seamless search-to-booking process, ensuring your next campaign not
            only resonates but also leaves a lasting impression. Explore your
            advertising possibilities today. Your audience is waiting.
          </p>
        </div>
      </div>
    </div>
    <div id="for_boardonwers" class="main_for_board_owners">
      <div class="for_boardonwers_container">
        <div class="boardonwers_text">
          <p>
            Greetings from HappyClient – where billboards meet their potential.
            As a valued board owner, you hold the key to a world of advertising
            opportunities, and we're here to unlock it together. Our platform
            specializes in bridging the gap between your billboard space and
            advertisers eager to make their mark. By listing with us, you not
            only enhance your billboard's visibility but also join a community
            dedicated to optimizing outdoor advertising spaces. Enjoy
            competitive returns, effortless management, and the flexibility to
            connect with a diverse pool of advertisers. With HappyClient, your
            billboard is more than a structure; it's a beacon for brands across
            the city. Ready to elevate your billboard's value? Let's embark on
            this journey together.
          </p>
        </div>
        <div class="for_boardonwers_content">
          <h1>FOR BOARD OWNERS</h1>
          <img src="{%static 'images/neon-city.jpg' %}" alt="for_board" />
          <a href="#" class="for-owners-button">GET STARTED</a>
        </div>
      </div>
    </div>

    <footer class="foot">
      <div class="page">
        <div class="logofooter">
          <img
            src="{%static 'images/logo.png'%}"
            alt="foto"
            width="60px"
            style="border-radius: 50%"
          />
          <span class="page-text">HappyClient</span>
        </div>
        <p class="info">Elevate Your Advertisement, Optimize Your Impact</p>
        <br /><br />

        <div class="icons">
          <img class="icon" src="{%static 'svg/twiter.svg'%}" alt="twitter" />
          <img
            class="icon"
            src="{%static 'svg/facebook.svg'%}"
            alt="facebook"
          />
          <img
            class="icon"
            src="{%static 'svg/instagram.svg'%}"
            alt="instagram"
          />
          <img
            class="icon"
            src="{%static 'svg/telegram.svg'%}"
            alt="telegram"
          />
        </div>
      </div>

      <div class="materials">
        <div class="resources">
          <ul class="site">
            <li>
              <p>Quick Links</p>
            </li>
            <li>
              <a href="#" class="web site">Home</a>
            </li>
            <li>
              <a href="#" class="web site">About Us</a>
            </li>
            <li>
              <a href="#" class="web site">Boards & Pricing</a>
            </li>
            <li>
              <a href="#" class="web site">Dashboard (For registered users)</a>
            </li>
            <li>
              <a href="#" class="web site">Privacy Policy</a>
            </li>
            <li>
              <a href="#" class="web site">Terms of Service</a>
            </li>
          </ul>

          <ul class="site">
            <li>
              <p>Contact Us</p>
            </li>
            <li>
              <a class="web site"
                >Address: 123 Advertising Blvd, Ad City, AC 12345</a
              >
            </li>
            <li>
              <a class="web site">Phone: (123) 456-7890</a>
            </li>
            <li>
              <a class="web site">Email: contact@billboardadvertising.com</a>
            </li>

            <li>
              <p>Get Started</p>
            </li>
            <li>
              <a class="web site">Board List</a>
            </li>
            <li>
              <a class="web site">Advertiser Sign-Up</a>
            </li>
          </ul>

          <ul class="site">
            <li>
              <p>Resources</p>
            </li>
            <li>
              <a href="#" class="web site">FAQs</a>
            </li>
            <li>
              <a href="#" class="web site">Blog</a>
            </li>
            <li>
              <a href="#" class="web site">Careers</a>
            </li>
          </ul>

          <div class="last-line"></div>
          <br /><br />

          <div class="number">
            <p>
              Copyright © 2024 Billboard Advertising Platform. All rights
              reserved.<br />
              Company Registration No. 123456789
            </p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

api/templates/api/registration.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <title>Registration</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/registration.css' %}" />
  </head>
  <body>
    <div class="content">
      <header class="header">
        <h1>HappyClient</h1>
      </header>
      <div class="wrapper">
        <div class="head">
          <img src="{%static 'images/logo.png'%}" alt="logo" />
          <h2>Sign up</h2>
          <p>
            Enter your details below to create your account and get started.
          </p>
        </div>
        <div class="form-outline">
          <form method="post">
            {% csrf_token %}
            <div class="inline">
              <div class="form-group">
                <label for="id_first_name">Name:</label>
                {{ form.first_name }}
              </div>
              <div class="form-group">
                <label for="id_last_name">Last Name:</label>
                {{ form.last_name }}
              </div>
              <div class="form-group">
                <label for="id_email">Email:</label>
                {{ form.email }} {% if form.errors.email %}
                <span class="error">{{ form.errors.email }}</span>
                {% endif %}
              </div>
              <div class="form-group">
                <label for="id_company_name">Username:</label>
                {{ form.username }} {% if form.errors.username %}
                <span class="error">{{ form.errors.username }}</span>
                {% endif %}
              </div>
              <div class="form-group">
                <label for="id_password">Password:</label>
                {{ form.password }}
              </div>
              <div class="form-group">
                <label for="id_phone_number">Password2:</label>
                {{ form.password1 }} {{ form.password1.errors }}
              </div>
            </div>
            <div class="buttons">
              <button
                type="reset"
                class="btn btn-primary cancel-btn p20"
                id="to_login"
              >
                Cancel
              </button>
              <button type="submit" class="btn btn-primary submit-btn">
                Submit
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
  <script>
    document.getElementById("to_login").onclick = function () {
      // Any logic you want to execute before redirecting
      window.location.href = "{%url 'login' %}";
    };
  </script>
</html>